// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Users.Infra;

#nullable disable

namespace Users.Migrations
{
  [DbContext(typeof(Db))]
  partial class DbModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "8.0.22")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("Users.src.Domain.Entities.User", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<DateTime>("CreatedAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<DateTime?>("DeletedAt")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasMaxLength(128)
                      .HasColumnType("character varying(128)")
                      .HasAnnotation("Relational:JsonPropertyName", "email");

            b.Property<bool>("IsAdmin")
                      .HasColumnType("boolean")
                      .HasAnnotation("Relational:JsonPropertyName", "isAdmin");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasMaxLength(64)
                      .HasColumnType("character varying(64)")
                      .HasAnnotation("Relational:JsonPropertyName", "name");

            b.Property<string>("Password")
                      .IsRequired()
                      .HasMaxLength(128)
                      .HasColumnType("character varying(128)")
                      .HasAnnotation("Relational:JsonPropertyName", "password");

            b.Property<DateTime?>("UpdatedAt")
                      .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("Email");

            b.ToTable("Users");
          });
#pragma warning restore 612, 618
    }
  }
}
